server:
  port: 7788 #服务端口
spring:
  application:
    name:  microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/mylove-yan/springcloud.git
          search-paths:
            - myspringcloudconfig		#配置文件目录地址
          username: 3747xxxx@qq.com	#码云账号（公有项目不需要设置）
          password: m86xxx 	#码云密码（公有项目不需要设置）
      label: master	#分支名称

